name: cosmonaut
description: A flutter news app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  equatable: ^1.2.6
  flutter_bloc: ^6.0.0
  get_it: ^4.0.2
  dartz: ^0.8.9  
  flutter_secure_storage: ^3.3.1+1
  http: ^0.12.0+3
  cached_network_image: ^2.5.0
  intl: ^0.16.1
  flutter_webview_plugin: ^0.3.11
  


dev_dependencies:
  json_serializable: ^3.5.1
  mockito: ^4.1.3
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:    
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
  uses-material-design: true      
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
